/**
 * seedIndoChinese.mjs
 * 
 * Two operations:
 * 1. REPLACE corrupt INDB Indo-Chinese entries (wrong per-100g values)
 * 2. ADD missing Indo-Chinese dishes
 *
 * Research sources (Indo-Chinese has no academic DB coverage - uniquely Indian fusion):
 *   - Tarladalal.com: Veg Manchurian dry=343kcal/serving, gravy=166kcal/serving, Manchow=114kcal/serving, Crispy Corn=483kcal/serving
 *   - ClearCals.com: Chicken 65=193kcal/100g, Veg Momos=113kcal/100g, Chicken Momos=159kcal/100g
 *   - SnapCalorie: Chicken Lollipop=250kcal/100g, Crispy Corn=500kcal/100g
 *   - USDA FoodData: Wonton Soup=32kcal/100g
 *   - Cross-referenced with Nutritionix restaurant data
 *
 * data_quality_score: 65 for all Indo-Chinese (no academic DB coverage, uniquely Indian fusion)
 * verified: false
 */

import path from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';
import mongoose from 'mongoose';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: path.resolve(__dirname, '../.env') });
dotenv.config({ path: path.resolve(__dirname, '../../.env') });

// -- CORRUPT INDB ENTRIES TO REPLACE ------------------------------------------
// These have wrong per-100g values in INDB (e.g. Chilli Paneer 778 kcal/100g = 78% fat, impossible)
// Replacing with research-based values from Tarladalal, ClearCals, SnapCalorie

const INDO_CHINESE_DISHES = [
  // REPLACEMENTS (corrupt INDB data)
  { canonical_name: "chilli paneer dry", display_name_en: "Chilli Paneer (Dry)", category: "snack", subcategory: "plate", cuisine_region: "indo_chinese", meal_type: "snack", cooking_method: "fried", is_veg: true, is_vegan: false, is_jain: false, allergens: ["dairy", "gluten", "soy"], glycemic_index: 50, data_source: "recipe_analysis_indo_chinese", data_quality_score: 65, verified: false, per_100g: { calories_kcal: 210, protein_g: 9.0, carbs_g: 12.0, fat_g: 14.0, fiber_g: 1.5, sugar_g: 3.5, sodium_mg: 580, saturated_fat_g: 5.5 }, portions: [{ label: "plate (restaurant ~250g)", weight_grams: 250, calories_kcal: 525, protein_g: 22.5, carbs_g: 30.0, fat_g: 35.0, fiber_g: 3.8, sodium_mg: 1450, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Indo-Chinese: already restaurant-calibrated values" }], aliases: [{ alias_text: "Chilli Paneer", language: "en", script: "latin" }, { alias_text: "Dry Chilli Paneer", language: "en", script: "latin" }] },
  { canonical_name: "chilli paneer gravy", display_name_en: "Chilli Paneer (Gravy)", category: "curry", subcategory: "bowl", cuisine_region: "indo_chinese", meal_type: "lunch_dinner", cooking_method: "fried", is_veg: true, is_vegan: false, is_jain: false, allergens: ["dairy", "gluten", "soy"], glycemic_index: 48, data_source: "recipe_analysis_indo_chinese", data_quality_score: 65, verified: false, per_100g: { calories_kcal: 165, protein_g: 8.0, carbs_g: 11.0, fat_g: 10.0, fiber_g: 1.2, sugar_g: 4.0, sodium_mg: 520, saturated_fat_g: 4.2 }, portions: [{ label: "bowl (restaurant ~280g)", weight_grams: 280, calories_kcal: 462, protein_g: 22.4, carbs_g: 30.8, fat_g: 28.0, fiber_g: 3.4, sodium_mg: 1456, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Indo-Chinese: already restaurant-calibrated values" }], aliases: [{ alias_text: "Paneer Chilli Gravy", language: "en", script: "latin" }] },
  { canonical_name: "veg manchurian dry", display_name_en: "Veg Manchurian (Dry)", category: "snack", subcategory: "plate", cuisine_region: "indo_chinese", meal_type: "snack", cooking_method: "fried", is_veg: true, is_vegan: true, is_jain: false, allergens: ["gluten", "soy"], glycemic_index: 52, data_source: "recipe_analysis_indo_chinese", data_quality_score: 65, verified: false, per_100g: { calories_kcal: 185, protein_g: 4.0, carbs_g: 18.0, fat_g: 11.0, fiber_g: 2.5, sugar_g: 4.5, sodium_mg: 520, saturated_fat_g: 1.5 }, portions: [{ label: "plate (restaurant ~200g)", weight_grams: 200, calories_kcal: 370, protein_g: 8.0, carbs_g: 36.0, fat_g: 22.0, fiber_g: 5.0, sodium_mg: 1040, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Indo-Chinese: already restaurant-calibrated values" }], aliases: [{ alias_text: "Vegetable Manchurian Dry", language: "en", script: "latin" }, { alias_text: "Manchurian Dry", language: "en", script: "latin" }] },
  { canonical_name: "veg manchurian gravy", display_name_en: "Veg Manchurian (Gravy)", category: "curry", subcategory: "bowl", cuisine_region: "indo_chinese", meal_type: "lunch_dinner", cooking_method: "fried", is_veg: true, is_vegan: true, is_jain: false, allergens: ["gluten", "soy"], glycemic_index: 48, data_source: "recipe_analysis_indo_chinese", data_quality_score: 65, verified: false, per_100g: { calories_kcal: 120, protein_g: 3.0, carbs_g: 14.0, fat_g: 6.0, fiber_g: 2.0, sugar_g: 5.0, sodium_mg: 480, saturated_fat_g: 0.8 }, portions: [{ label: "bowl (restaurant ~280g)", weight_grams: 280, calories_kcal: 336, protein_g: 8.4, carbs_g: 39.2, fat_g: 16.8, fiber_g: 5.6, sodium_mg: 1344, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Indo-Chinese: already restaurant-calibrated values" }], aliases: [{ alias_text: "Vegetable Manchurian Gravy", language: "en", script: "latin" }, { alias_text: "Manchurian Gravy", language: "en", script: "latin" }] },
  { canonical_name: "gobi 65", display_name_en: "Gobi 65", category: "snack", subcategory: "plate", cuisine_region: "south_indian", meal_type: "snack", cooking_method: "fried", is_veg: true, is_vegan: true, is_jain: false, allergens: ["gluten"], glycemic_index: 55, data_source: "recipe_analysis_indo_chinese", data_quality_score: 65, verified: false, per_100g: { calories_kcal: 220, protein_g: 4.0, carbs_g: 18.0, fat_g: 15.0, fiber_g: 2.0, sugar_g: 2.5, sodium_mg: 480, saturated_fat_g: 1.8 }, portions: [{ label: "plate (restaurant ~200g)", weight_grams: 200, calories_kcal: 440, protein_g: 8.0, carbs_g: 36.0, fat_g: 30.0, fiber_g: 4.0, sodium_mg: 960, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Indo-Chinese: already restaurant-calibrated values" }], aliases: [{ alias_text: "Cauliflower 65", language: "en", script: "latin" }, { alias_text: "Gobi Fry", language: "en", script: "latin" }] },
  { canonical_name: "veg spring roll", display_name_en: "Veg Spring Roll", category: "snack", subcategory: "spring roll", cuisine_region: "indo_chinese", meal_type: "snack", cooking_method: "fried", is_veg: true, is_vegan: true, is_jain: false, allergens: ["gluten", "soy"], glycemic_index: 55, data_source: "recipe_analysis_indo_chinese", data_quality_score: 65, verified: false, per_100g: { calories_kcal: 195, protein_g: 4.0, carbs_g: 22.0, fat_g: 10.0, fiber_g: 2.0, sugar_g: 2.0, sodium_mg: 420, saturated_fat_g: 1.5 }, portions: [{ label: "spring roll (2 pieces ~120g)", weight_grams: 120, calories_kcal: 234, protein_g: 4.8, carbs_g: 26.4, fat_g: 12.0, fiber_g: 2.4, sodium_mg: 504, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Indo-Chinese: already restaurant-calibrated values" }], aliases: [{ alias_text: "Vegetable Spring Roll", language: "en", script: "latin" }, { alias_text: "Spring Roll Veg", language: "en", script: "latin" }] },
  { canonical_name: "chicken sweet and sour", display_name_en: "Chicken Sweet and Sour", category: "curry", subcategory: "bowl", cuisine_region: "indo_chinese", meal_type: "lunch_dinner", cooking_method: "fried", is_veg: false, is_vegan: false, is_jain: false, allergens: ["gluten", "soy"], glycemic_index: 55, data_source: "recipe_analysis_indo_chinese", data_quality_score: 65, verified: false, per_100g: { calories_kcal: 148, protein_g: 10.0, carbs_g: 16.0, fat_g: 5.5, fiber_g: 1.0, sugar_g: 8.0, sodium_mg: 520, saturated_fat_g: 1.2 }, portions: [{ label: "bowl (restaurant ~280g)", weight_grams: 280, calories_kcal: 414, protein_g: 28.0, carbs_g: 44.8, fat_g: 15.4, fiber_g: 2.8, sodium_mg: 1456, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Indo-Chinese: already restaurant-calibrated values" }], aliases: [{ alias_text: "Sweet Sour Chicken", language: "en", script: "latin" }] },
  // NEW ADDITIONS - Missing Indo-Chinese dishes
  // Source: ClearCals (Chicken 65=193kcal/100g, Veg Momos=113kcal/100g, Chicken Momos=159kcal/100g)
  // Tarladalal (Manchow=114kcal/serving, Crispy Corn=483kcal/serving)
  // USDA (Wonton Soup=32kcal/100g), SnapCalorie (Chicken Lollipop=250kcal/100g)
  { canonical_name: "hakka noodles veg", display_name_en: "Hakka Noodles (Veg)", category: "other", subcategory: "plate", cuisine_region: "indo_chinese", meal_type: "lunch_dinner", cooking_method: "fried", is_veg: true, is_vegan: true, is_jain: false, allergens: ["gluten", "soy"], glycemic_index: 55, data_source: "recipe_analysis_indo_chinese", data_quality_score: 65, verified: false, per_100g: { calories_kcal: 145, protein_g: 4.0, carbs_g: 22.0, fat_g: 5.0, fiber_g: 1.8, sugar_g: 2.5, sodium_mg: 520, saturated_fat_g: 0.8 }, portions: [{ label: "plate (restaurant ~300g)", weight_grams: 300, calories_kcal: 435, protein_g: 12.0, carbs_g: 66.0, fat_g: 15.0, fiber_g: 5.4, sodium_mg: 1560, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Indo-Chinese: already restaurant-calibrated values" }], aliases: [{ alias_text: "Veg Hakka Noodles", language: "en", script: "latin" }, { alias_text: "Chinese Noodles Veg", language: "en", script: "latin" }] },
  { canonical_name: "hakka noodles chicken", display_name_en: "Hakka Noodles (Chicken)", category: "other", subcategory: "plate", cuisine_region: "indo_chinese", meal_type: "lunch_dinner", cooking_method: "fried", is_veg: false, is_vegan: false, is_jain: false, allergens: ["gluten", "soy", "eggs"], glycemic_index: 55, data_source: "recipe_analysis_indo_chinese", data_quality_score: 65, verified: false, per_100g: { calories_kcal: 158, protein_g: 9.0, carbs_g: 20.0, fat_g: 5.0, fiber_g: 1.5, sugar_g: 2.0, sodium_mg: 540, saturated_fat_g: 1.0 }, portions: [{ label: "plate (restaurant ~300g)", weight_grams: 300, calories_kcal: 474, protein_g: 27.0, carbs_g: 60.0, fat_g: 15.0, fiber_g: 4.5, sodium_mg: 1620, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Indo-Chinese: already restaurant-calibrated values" }], aliases: [{ alias_text: "Chicken Hakka Noodles", language: "en", script: "latin" }] },
  { canonical_name: "schezwan noodles", display_name_en: "Schezwan Noodles", category: "other", subcategory: "plate", cuisine_region: "indo_chinese", meal_type: "lunch_dinner", cooking_method: "fried", is_veg: true, is_vegan: true, is_jain: false, allergens: ["gluten", "soy"], glycemic_index: 55, data_source: "recipe_analysis_indo_chinese", data_quality_score: 65, verified: false, per_100g: { calories_kcal: 162, protein_g: 4.0, carbs_g: 23.0, fat_g: 6.0, fiber_g: 1.8, sugar_g: 2.8, sodium_mg: 580, saturated_fat_g: 0.8 }, portions: [{ label: "plate (restaurant ~300g)", weight_grams: 300, calories_kcal: 486, protein_g: 12.0, carbs_g: 69.0, fat_g: 18.0, fiber_g: 5.4, sodium_mg: 1740, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Indo-Chinese: already restaurant-calibrated values" }], aliases: [{ alias_text: "Szechwan Noodles", language: "en", script: "latin" }, { alias_text: "Schezwan Fried Noodles", language: "en", script: "latin" }] },
  { canonical_name: "schezwan fried rice", display_name_en: "Schezwan Fried Rice", category: "rice_dish", subcategory: "plate", cuisine_region: "indo_chinese", meal_type: "lunch_dinner", cooking_method: "fried", is_veg: true, is_vegan: true, is_jain: false, allergens: ["soy"], glycemic_index: 65, data_source: "recipe_analysis_indo_chinese", data_quality_score: 65, verified: false, per_100g: { calories_kcal: 155, protein_g: 3.5, carbs_g: 25.0, fat_g: 5.0, fiber_g: 1.0, sugar_g: 2.0, sodium_mg: 560, saturated_fat_g: 0.8 }, portions: [{ label: "plate (restaurant ~300g)", weight_grams: 300, calories_kcal: 465, protein_g: 10.5, carbs_g: 75.0, fat_g: 15.0, fiber_g: 3.0, sodium_mg: 1680, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Indo-Chinese: already restaurant-calibrated values" }], aliases: [{ alias_text: "Szechwan Fried Rice", language: "en", script: "latin" }] },
  { canonical_name: "egg fried rice", display_name_en: "Egg Fried Rice", category: "rice_dish", subcategory: "plate", cuisine_region: "indo_chinese", meal_type: "lunch_dinner", cooking_method: "fried", is_veg: false, is_vegan: false, is_jain: false, allergens: ["eggs", "soy"], glycemic_index: 65, data_source: "recipe_analysis_indo_chinese", data_quality_score: 65, verified: false, per_100g: { calories_kcal: 148, protein_g: 5.5, carbs_g: 22.0, fat_g: 5.0, fiber_g: 0.8, sugar_g: 1.5, sodium_mg: 460, saturated_fat_g: 1.2 }, portions: [{ label: "plate (restaurant ~300g)", weight_grams: 300, calories_kcal: 444, protein_g: 16.5, carbs_g: 66.0, fat_g: 15.0, fiber_g: 2.4, sodium_mg: 1380, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Indo-Chinese: already restaurant-calibrated values" }], aliases: [{ alias_text: "Anda Fried Rice", language: "en", script: "latin" }] },
  { canonical_name: "paneer fried rice", display_name_en: "Paneer Fried Rice", category: "rice_dish", subcategory: "plate", cuisine_region: "indo_chinese", meal_type: "lunch_dinner", cooking_method: "fried", is_veg: true, is_vegan: false, is_jain: false, allergens: ["dairy", "soy"], glycemic_index: 62, data_source: "recipe_analysis_indo_chinese", data_quality_score: 65, verified: false, per_100g: { calories_kcal: 155, protein_g: 5.5, carbs_g: 22.5, fat_g: 5.5, fiber_g: 0.8, sugar_g: 1.5, sodium_mg: 440, saturated_fat_g: 2.0 }, portions: [{ label: "plate (restaurant ~300g)", weight_grams: 300, calories_kcal: 465, protein_g: 16.5, carbs_g: 67.5, fat_g: 16.5, fiber_g: 2.4, sodium_mg: 1320, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Indo-Chinese: already restaurant-calibrated values" }], aliases: [{ alias_text: "Paneer Chinese Rice", language: "en", script: "latin" }] },
  { canonical_name: "chicken 65", display_name_en: "Chicken 65", category: "snack", subcategory: "plate", cuisine_region: "south_indian", meal_type: "snack", cooking_method: "fried", is_veg: false, is_vegan: false, is_jain: false, allergens: ["gluten"], glycemic_index: 45, data_source: "recipe_analysis_indo_chinese", data_quality_score: 68, verified: false, per_100g: { calories_kcal: 193, protein_g: 12.6, carbs_g: 2.4, fat_g: 15.3, fiber_g: 0.5, sugar_g: 0.8, sodium_mg: 520, saturated_fat_g: 3.5 }, portions: [{ label: "plate (restaurant ~200g)", weight_grams: 200, calories_kcal: 386, protein_g: 25.2, carbs_g: 4.8, fat_g: 30.6, fiber_g: 1.0, sodium_mg: 1040, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Indo-Chinese: already restaurant-calibrated values" }], aliases: [{ alias_text: "Chicken Sixty Five", language: "en", script: "latin" }] },
  { canonical_name: "paneer 65", display_name_en: "Paneer 65", category: "snack", subcategory: "plate", cuisine_region: "south_indian", meal_type: "snack", cooking_method: "fried", is_veg: true, is_vegan: false, is_jain: false, allergens: ["dairy", "gluten"], glycemic_index: 48, data_source: "recipe_analysis_indo_chinese", data_quality_score: 65, verified: false, per_100g: { calories_kcal: 235, protein_g: 9.5, carbs_g: 8.0, fat_g: 18.5, fiber_g: 0.5, sugar_g: 1.5, sodium_mg: 480, saturated_fat_g: 7.5 }, portions: [{ label: "plate (restaurant ~200g)", weight_grams: 200, calories_kcal: 470, protein_g: 19.0, carbs_g: 16.0, fat_g: 37.0, fiber_g: 1.0, sodium_mg: 960, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Indo-Chinese: already restaurant-calibrated values" }], aliases: [{ alias_text: "Paneer Sixty Five", language: "en", script: "latin" }] },
  { canonical_name: "mushroom 65", display_name_en: "Mushroom 65", category: "snack", subcategory: "plate", cuisine_region: "south_indian", meal_type: "snack", cooking_method: "fried", is_veg: true, is_vegan: true, is_jain: false, allergens: ["gluten"], glycemic_index: 50, data_source: "recipe_analysis_indo_chinese", data_quality_score: 65, verified: false, per_100g: { calories_kcal: 185, protein_g: 4.5, carbs_g: 12.0, fat_g: 13.5, fiber_g: 1.5, sugar_g: 2.0, sodium_mg: 460, saturated_fat_g: 1.5 }, portions: [{ label: "plate (restaurant ~200g)", weight_grams: 200, calories_kcal: 370, protein_g: 9.0, carbs_g: 24.0, fat_g: 27.0, fiber_g: 3.0, sodium_mg: 920, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Indo-Chinese: already restaurant-calibrated values" }], aliases: [{ alias_text: "Mushroom Sixty Five", language: "en", script: "latin" }] },
  { canonical_name: "chilli mushroom", display_name_en: "Chilli Mushroom", category: "snack", subcategory: "plate", cuisine_region: "indo_chinese", meal_type: "snack", cooking_method: "fried", is_veg: true, is_vegan: true, is_jain: false, allergens: ["gluten", "soy"], glycemic_index: 48, data_source: "recipe_analysis_indo_chinese", data_quality_score: 65, verified: false, per_100g: { calories_kcal: 145, protein_g: 4.0, carbs_g: 12.0, fat_g: 9.0, fiber_g: 1.8, sugar_g: 4.0, sodium_mg: 540, saturated_fat_g: 1.2 }, portions: [{ label: "plate (restaurant ~250g)", weight_grams: 250, calories_kcal: 363, protein_g: 10.0, carbs_g: 30.0, fat_g: 22.5, fiber_g: 4.5, sodium_mg: 1350, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Indo-Chinese: already restaurant-calibrated values" }], aliases: [{ alias_text: "Mushroom Chilli", language: "en", script: "latin" }] },
  { canonical_name: "chilli fish", display_name_en: "Chilli Fish", category: "snack", subcategory: "plate", cuisine_region: "indo_chinese", meal_type: "snack", cooking_method: "fried", is_veg: false, is_vegan: false, is_jain: false, allergens: ["fish", "gluten", "soy"], glycemic_index: 45, data_source: "recipe_analysis_indo_chinese", data_quality_score: 65, verified: false, per_100g: { calories_kcal: 175, protein_g: 14.0, carbs_g: 10.0, fat_g: 9.0, fiber_g: 0.8, sugar_g: 3.5, sodium_mg: 560, saturated_fat_g: 1.8 }, portions: [{ label: "plate (restaurant ~250g)", weight_grams: 250, calories_kcal: 438, protein_g: 35.0, carbs_g: 25.0, fat_g: 22.5, fiber_g: 2.0, sodium_mg: 1400, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Indo-Chinese: already restaurant-calibrated values" }], aliases: [{ alias_text: "Fish Chilli", language: "en", script: "latin" }] },
  { canonical_name: "chilli garlic noodles", display_name_en: "Chilli Garlic Noodles", category: "other", subcategory: "plate", cuisine_region: "indo_chinese", meal_type: "lunch_dinner", cooking_method: "fried", is_veg: true, is_vegan: true, is_jain: false, allergens: ["gluten", "soy"], glycemic_index: 55, data_source: "recipe_analysis_indo_chinese", data_quality_score: 65, verified: false, per_100g: { calories_kcal: 168, protein_g: 4.5, carbs_g: 24.0, fat_g: 6.5, fiber_g: 1.5, sugar_g: 2.0, sodium_mg: 580, saturated_fat_g: 0.8 }, portions: [{ label: "plate (restaurant ~300g)", weight_grams: 300, calories_kcal: 504, protein_g: 13.5, carbs_g: 72.0, fat_g: 19.5, fiber_g: 4.5, sodium_mg: 1740, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Indo-Chinese: already restaurant-calibrated values" }], aliases: [{ alias_text: "Garlic Chilli Noodles", language: "en", script: "latin" }] },
  { canonical_name: "american chopsuey", display_name_en: "American Chopsuey", category: "other", subcategory: "plate", cuisine_region: "indo_chinese", meal_type: "lunch_dinner", cooking_method: "fried", is_veg: true, is_vegan: false, is_jain: false, allergens: ["gluten", "soy", "eggs"], glycemic_index: 60, data_source: "recipe_analysis_indo_chinese", data_quality_score: 65, verified: false, per_100g: { calories_kcal: 168, protein_g: 5.0, carbs_g: 26.0, fat_g: 5.0, fiber_g: 1.5, sugar_g: 5.0, sodium_mg: 480, saturated_fat_g: 1.0 }, portions: [{ label: "plate (restaurant ~350g)", weight_grams: 350, calories_kcal: 588, protein_g: 17.5, carbs_g: 91.0, fat_g: 17.5, fiber_g: 5.3, sodium_mg: 1680, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Indo-Chinese: already restaurant-calibrated values" }], aliases: [{ alias_text: "Chopsuey", language: "en", script: "latin" }, { alias_text: "Chop Suey", language: "en", script: "latin" }] },
  { canonical_name: "chicken lollipop", display_name_en: "Chicken Lollipop", category: "snack", subcategory: "piece", cuisine_region: "indo_chinese", meal_type: "snack", cooking_method: "fried", is_veg: false, is_vegan: false, is_jain: false, allergens: ["gluten"], glycemic_index: 45, data_source: "recipe_analysis_indo_chinese", data_quality_score: 65, verified: false, per_100g: { calories_kcal: 265, protein_g: 16.0, carbs_g: 10.0, fat_g: 18.0, fiber_g: 0.5, sugar_g: 1.5, sodium_mg: 520, saturated_fat_g: 4.0 }, portions: [{ label: "plate (6 pieces ~200g)", weight_grams: 200, calories_kcal: 530, protein_g: 32.0, carbs_g: 20.0, fat_g: 36.0, fiber_g: 1.0, sodium_mg: 1040, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Indo-Chinese: already restaurant-calibrated values" }], aliases: [{ alias_text: "Lollipop Chicken", language: "en", script: "latin" }] },
  { canonical_name: "crispy corn", display_name_en: "Crispy Corn", category: "snack", subcategory: "plate", cuisine_region: "indo_chinese", meal_type: "snack", cooking_method: "fried", is_veg: true, is_vegan: true, is_jain: false, allergens: ["gluten"], glycemic_index: 65, data_source: "recipe_analysis_indo_chinese", data_quality_score: 65, verified: false, per_100g: { calories_kcal: 310, protein_g: 4.0, carbs_g: 38.0, fat_g: 16.0, fiber_g: 3.5, sugar_g: 3.0, sodium_mg: 380, saturated_fat_g: 1.5 }, portions: [{ label: "plate (restaurant ~150g)", weight_grams: 150, calories_kcal: 465, protein_g: 6.0, carbs_g: 57.0, fat_g: 24.0, fiber_g: 5.3, sodium_mg: 570, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Indo-Chinese: already restaurant-calibrated values" }], aliases: [{ alias_text: "Crispy Fried Corn", language: "en", script: "latin" }] },
  { canonical_name: "chicken spring roll", display_name_en: "Chicken Spring Roll", category: "snack", subcategory: "spring roll", cuisine_region: "indo_chinese", meal_type: "snack", cooking_method: "fried", is_veg: false, is_vegan: false, is_jain: false, allergens: ["gluten", "soy"], glycemic_index: 52, data_source: "recipe_analysis_indo_chinese", data_quality_score: 65, verified: false, per_100g: { calories_kcal: 215, protein_g: 9.0, carbs_g: 20.0, fat_g: 11.0, fiber_g: 1.5, sugar_g: 2.0, sodium_mg: 460, saturated_fat_g: 2.0 }, portions: [{ label: "spring roll (2 pieces ~120g)", weight_grams: 120, calories_kcal: 258, protein_g: 10.8, carbs_g: 24.0, fat_g: 13.2, fiber_g: 1.8, sodium_mg: 552, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Indo-Chinese: already restaurant-calibrated values" }], aliases: [{ alias_text: "Chicken Roll", language: "en", script: "latin" }] },
  { canonical_name: "momos steamed veg", display_name_en: "Veg Momos (Steamed)", category: "snack", subcategory: "piece", cuisine_region: "indo_chinese", meal_type: "snack", cooking_method: "steamed", is_veg: true, is_vegan: true, is_jain: false, allergens: ["gluten"], glycemic_index: 45, data_source: "recipe_analysis_indo_chinese", data_quality_score: 68, verified: false, per_100g: { calories_kcal: 113, protein_g: 1.2, carbs_g: 6.4, fat_g: 0.5, fiber_g: 1.2, sugar_g: 1.0, sodium_mg: 280, saturated_fat_g: 0.1 }, portions: [{ label: "plate (6 pieces ~180g)", weight_grams: 180, calories_kcal: 203, protein_g: 2.2, carbs_g: 11.5, fat_g: 0.9, fiber_g: 2.2, sodium_mg: 504, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Steamed: no added fat, minimal adjustment" }], aliases: [{ alias_text: "Veg Momo", language: "en", script: "latin" }, { alias_text: "Steamed Veg Dumplings", language: "en", script: "latin" }] },
  { canonical_name: "momos steamed chicken", display_name_en: "Chicken Momos (Steamed)", category: "snack", subcategory: "piece", cuisine_region: "indo_chinese", meal_type: "snack", cooking_method: "steamed", is_veg: false, is_vegan: false, is_jain: false, allergens: ["gluten"], glycemic_index: 45, data_source: "recipe_analysis_indo_chinese", data_quality_score: 68, verified: false, per_100g: { calories_kcal: 159, protein_g: 2.4, carbs_g: 5.8, fat_g: 1.7, fiber_g: 0.8, sugar_g: 0.8, sodium_mg: 320, saturated_fat_g: 0.5 }, portions: [{ label: "plate (6 pieces ~180g)", weight_grams: 180, calories_kcal: 286, protein_g: 4.3, carbs_g: 10.4, fat_g: 3.1, fiber_g: 1.4, sodium_mg: 576, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Steamed: no added fat, minimal adjustment" }], aliases: [{ alias_text: "Chicken Momo", language: "en", script: "latin" }, { alias_text: "Steamed Chicken Dumplings", language: "en", script: "latin" }] },
  { canonical_name: "momos fried veg", display_name_en: "Veg Momos (Fried)", category: "snack", subcategory: "piece", cuisine_region: "indo_chinese", meal_type: "snack", cooking_method: "fried", is_veg: true, is_vegan: true, is_jain: false, allergens: ["gluten"], glycemic_index: 52, data_source: "recipe_analysis_indo_chinese", data_quality_score: 65, verified: false, per_100g: { calories_kcal: 185, protein_g: 1.2, carbs_g: 8.0, fat_g: 11.0, fiber_g: 1.0, sugar_g: 1.0, sodium_mg: 320, saturated_fat_g: 1.5 }, portions: [{ label: "plate (6 pieces ~180g)", weight_grams: 180, calories_kcal: 333, protein_g: 2.2, carbs_g: 14.4, fat_g: 19.8, fiber_g: 1.8, sodium_mg: 576, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Indo-Chinese: already restaurant-calibrated values" }], aliases: [{ alias_text: "Fried Veg Momo", language: "en", script: "latin" }, { alias_text: "Pan Fried Momos", language: "en", script: "latin" }] },
  { canonical_name: "manchow soup", display_name_en: "Manchow Soup", category: "soup", subcategory: "soup bowl", cuisine_region: "indo_chinese", meal_type: "lunch_dinner", cooking_method: "boiled", is_veg: true, is_vegan: true, is_jain: false, allergens: ["gluten", "soy"], glycemic_index: 35, data_source: "recipe_analysis_indo_chinese", data_quality_score: 68, verified: false, per_100g: { calories_kcal: 45, protein_g: 2.5, carbs_g: 5.0, fat_g: 2.0, fiber_g: 0.8, sugar_g: 1.5, sodium_mg: 480, saturated_fat_g: 0.3 }, portions: [{ label: "soup bowl (restaurant ~300ml)", weight_grams: 300, calories_kcal: 135, protein_g: 7.5, carbs_g: 15.0, fat_g: 6.0, fiber_g: 2.4, sodium_mg: 1440, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Soup: standardized recipe, minimal adjustment" }], aliases: [{ alias_text: "Manchow Soup Veg", language: "en", script: "latin" }] },
  { canonical_name: "wonton soup", display_name_en: "Wonton Soup", category: "soup", subcategory: "soup bowl", cuisine_region: "indo_chinese", meal_type: "lunch_dinner", cooking_method: "boiled", is_veg: false, is_vegan: false, is_jain: false, allergens: ["gluten", "soy"], glycemic_index: 35, data_source: "recipe_analysis_indo_chinese", data_quality_score: 68, verified: false, per_100g: { calories_kcal: 32, protein_g: 2.5, carbs_g: 4.5, fat_g: 0.6, fiber_g: 0.3, sugar_g: 0.8, sodium_mg: 420, saturated_fat_g: 0.2 }, portions: [{ label: "soup bowl (restaurant ~300ml)", weight_grams: 300, calories_kcal: 96, protein_g: 7.5, carbs_g: 13.5, fat_g: 1.8, fiber_g: 0.9, sodium_mg: 1260, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Soup: standardized recipe, minimal adjustment" }], aliases: [{ alias_text: "Wonton Soup Chinese", language: "en", script: "latin" }] },
];

async function seed() {
  const MONGODB_URI = process.env.MONGODB_URI;
  if (!MONGODB_URI) { console.error("[seed:indo] MONGODB_URI not found."); process.exit(1); }
  console.log("[seed:indo] Connecting to MongoDB...");
  await mongoose.connect(MONGODB_URI);
  console.log("[seed:indo] Connected.");
  const { default: FoodItem } = await import("../models/FoodItem.model.js");
  let upserted = 0, errors = 0;
  for (const dish of INDO_CHINESE_DISHES) {
    try {
      await FoodItem.updateOne({ canonical_name: dish.canonical_name }, { $set: { ...dish, last_updated: new Date() } }, { upsert: true });
      upserted++;
    } catch (err) {
      errors++;
      console.error(`[seed:indo] Error on "${dish.display_name_en}":`, err.message);
    }
  }
  console.log(`\n[seed:indo] Done! Upserted: ${upserted}/${INDO_CHINESE_DISHES.length}, Errors: ${errors}`);
  await mongoose.disconnect();
  process.exit(0);
}
seed().catch(err => { console.error("[seed:indo] Fatal:", err); process.exit(1); });
