import path from "path"; import { fileURLToPath } from "url"; import dotenv from "dotenv"; import mongoose from "mongoose"; const __dirname = path.dirname(fileURLToPath(import.meta.url)); dotenv.config({ path: path.resolve(__dirname, "../.env") }); dotenv.config({ path: path.resolve(__dirname, "../../.env") }); const STREET_FOOD_DISHES = [
  // REPLACEMENTS - Corrupt INDB entries (wrong per-100g values)
  // Bhel Puri: INDB=510kcal/100g (wrong). Tarladalal Mumbai Bhel=289kcal/serving (~180kcal/100g)
  { canonical_name: "bhel puri", display_name_en: "Bhel Puri", category: "snack", subcategory: "plate", cuisine_region: "south_indian", meal_type: "snack", cooking_method: "raw", is_veg: true, is_vegan: true, is_jain: false, allergens: ["gluten", "peanuts"], glycemic_index: 55, data_source: "recipe_analysis", data_quality_score: 80, verified: false, per_100g: { calories_kcal: 180, protein_g: 5.5, carbs_g: 28.0, fat_g: 6.5, fiber_g: 3.5, sugar_g: 4.0, sodium_mg: 280, saturated_fat_g: 1.0 }, portions: [{ label: "plate (restaurant ~250g)", weight_grams: 250, calories_kcal: 450, protein_g: 13.8, carbs_g: 70.0, fat_g: 16.3, fiber_g: 8.8, sodium_mg: 700, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Chaat: already restaurant-calibrated from Tarladalal" }], aliases: [{ alias_text: "Bhelpuri", language: "en", script: "latin" }, { alias_text: "Mumbai Bhel", language: "en", script: "latin" }] },
  // Masala Vada: INDB=826kcal/100g (impossible). ClearCals=252kcal/100g, Tarladalal=99kcal/piece
  { canonical_name: "masala vada", display_name_en: "Masala Vada", category: "snack", subcategory: "vada", cuisine_region: "south_indian", meal_type: "snack", cooking_method: "fried", is_veg: true, is_vegan: true, is_jain: false, allergens: ["gluten"], glycemic_index: 36, data_source: "recipe_analysis", data_quality_score: 80, verified: false, per_100g: { calories_kcal: 310, protein_g: 8.0, carbs_g: 28.0, fat_g: 18.0, fiber_g: 3.5, sugar_g: 1.5, sodium_mg: 380, saturated_fat_g: 2.5 }, portions: [{ label: "vada (1 piece ~50g)", weight_grams: 50, calories_kcal: 155, protein_g: 4.0, carbs_g: 14.0, fat_g: 9.0, fiber_g: 1.8, sodium_mg: 190, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Tarladalal verified: 99kcal/piece" }], aliases: [{ alias_text: "Dal Vada", language: "en", script: "latin" }, { alias_text: "Parippu Vada", language: "en", script: "latin" }] },
  // Dahi Vada: INDB=668kcal/100g (wrong by 4x). Tarladalal=106kcal/serving, ClearCals=200kcal/100g
  { canonical_name: "dahi vada", display_name_en: "Dahi Vada", category: "snack", subcategory: "plate", cuisine_region: "north_indian", meal_type: "snack", cooking_method: "fried", is_veg: true, is_vegan: false, is_jain: false, allergens: ["dairy", "gluten"], glycemic_index: 46, data_source: "recipe_analysis", data_quality_score: 80, verified: false, per_100g: { calories_kcal: 155, protein_g: 7.0, carbs_g: 20.0, fat_g: 5.0, fiber_g: 1.5, sugar_g: 5.0, sodium_mg: 220, saturated_fat_g: 2.0 }, portions: [{ label: "plate (restaurant ~250g)", weight_grams: 250, calories_kcal: 388, protein_g: 17.5, carbs_g: 50.0, fat_g: 12.5, fiber_g: 3.8, sodium_mg: 550, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Tarladalal verified: 106kcal/serving" }], aliases: [{ alias_text: "Dahi Bhalla", language: "en", script: "latin" }, { alias_text: "Dahi Bhalle", language: "en", script: "latin" }] },
  // Vegetable Burger: INDB=520kcal/100g (wrong). Realistic ~230kcal/100g
  { canonical_name: "vegetable burger", display_name_en: "Vegetable Burger", category: "snack", subcategory: "burger", cuisine_region: "continental", meal_type: "snack", cooking_method: "fried", is_veg: true, is_vegan: false, is_jain: false, allergens: ["gluten", "dairy"], glycemic_index: 60, data_source: "recipe_analysis", data_quality_score: 70, verified: false, per_100g: { calories_kcal: 230, protein_g: 6.5, carbs_g: 30.0, fat_g: 10.0, fiber_g: 2.5, sugar_g: 4.0, sodium_mg: 480, saturated_fat_g: 3.0 }, portions: [{ label: "burger (1 piece ~180g)", weight_grams: 180, calories_kcal: 414, protein_g: 11.7, carbs_g: 54.0, fat_g: 18.0, fiber_g: 4.5, sodium_mg: 864, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Restaurant-calibrated value" }], aliases: [{ alias_text: "Veg Burger", language: "en", script: "latin" }] },
  // CHAAT - Core category (Tarladalal + ClearCals verified)
  { canonical_name: "raj kachori", display_name_en: "Raj Kachori", category: "snack", subcategory: "kachori", cuisine_region: "north_indian", meal_type: "snack", cooking_method: "fried", is_veg: true, is_vegan: false, is_jain: false, allergens: ["gluten", "dairy"], glycemic_index: 58, data_source: "recipe_analysis", data_quality_score: 80, verified: false, per_100g: { calories_kcal: 285, protein_g: 8.0, carbs_g: 32.0, fat_g: 14.0, fiber_g: 4.5, sugar_g: 5.0, sodium_mg: 320, saturated_fat_g: 3.5 }, portions: [{ label: "kachori (1 piece ~200g)", weight_grams: 200, calories_kcal: 570, protein_g: 16.0, carbs_g: 64.0, fat_g: 28.0, fiber_g: 9.0, sodium_mg: 640, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Tarladalal verified: 571kcal/serving" }], aliases: [{ alias_text: "Raj Kachori Chaat", language: "en", script: "latin" }] },
  { canonical_name: "aloo tikki chaat", display_name_en: "Aloo Tikki Chaat", category: "snack", subcategory: "plate", cuisine_region: "north_indian", meal_type: "snack", cooking_method: "fried", is_veg: true, is_vegan: false, is_jain: false, allergens: ["dairy", "gluten"], glycemic_index: 62, data_source: "recipe_analysis", data_quality_score: 75, verified: false, per_100g: { calories_kcal: 188, protein_g: 5.0, carbs_g: 26.0, fat_g: 8.0, fiber_g: 2.5, sugar_g: 5.5, sodium_mg: 380, saturated_fat_g: 2.5 }, portions: [{ label: "plate (restaurant ~250g)", weight_grams: 250, calories_kcal: 470, protein_g: 12.5, carbs_g: 65.0, fat_g: 20.0, fiber_g: 6.3, sodium_mg: 950, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Recipe analysis cross-referenced" }], aliases: [{ alias_text: "Tikki Chaat", language: "en", script: "latin" }] },
  { canonical_name: "aloo chaat", display_name_en: "Aloo Chaat", category: "snack", subcategory: "plate", cuisine_region: "north_indian", meal_type: "snack", cooking_method: "fried", is_veg: true, is_vegan: true, is_jain: false, allergens: [], glycemic_index: 60, data_source: "recipe_analysis", data_quality_score: 80, verified: false, per_100g: { calories_kcal: 175, protein_g: 3.0, carbs_g: 25.0, fat_g: 7.0, fiber_g: 2.5, sugar_g: 3.5, sodium_mg: 350, saturated_fat_g: 1.0 }, portions: [{ label: "plate (restaurant ~200g)", weight_grams: 200, calories_kcal: 350, protein_g: 6.0, carbs_g: 50.0, fat_g: 14.0, fiber_g: 5.0, sodium_mg: 700, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Tarladalal verified: 212kcal/serving" }], aliases: [{ alias_text: "Potato Chaat", language: "en", script: "latin" }] },
  { canonical_name: "matar kulcha", display_name_en: "Matar Kulcha", category: "snack", subcategory: "plate", cuisine_region: "north_indian", meal_type: "breakfast", cooking_method: "boiled", is_veg: true, is_vegan: true, is_jain: false, allergens: ["gluten"], glycemic_index: 58, data_source: "recipe_analysis", data_quality_score: 70, verified: false, per_100g: { calories_kcal: 198, protein_g: 7.0, carbs_g: 32.0, fat_g: 5.0, fiber_g: 4.0, sugar_g: 2.0, sodium_mg: 380, saturated_fat_g: 0.8 }, portions: [{ label: "plate (restaurant ~280g)", weight_grams: 280, calories_kcal: 554, protein_g: 19.6, carbs_g: 89.6, fat_g: 14.0, fiber_g: 11.2, sodium_mg: 1064, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Recipe analysis" }], aliases: [{ alias_text: "Matar Kulche", language: "en", script: "latin" }] },
  { canonical_name: "basket chaat", display_name_en: "Basket Chaat", category: "snack", subcategory: "plate", cuisine_region: "north_indian", meal_type: "snack", cooking_method: "fried", is_veg: true, is_vegan: false, is_jain: false, allergens: ["gluten", "dairy"], glycemic_index: 60, data_source: "recipe_analysis", data_quality_score: 65, verified: false, per_100g: { calories_kcal: 230, protein_g: 6.0, carbs_g: 30.0, fat_g: 10.0, fiber_g: 2.5, sugar_g: 5.5, sodium_mg: 380, saturated_fat_g: 3.0 }, portions: [{ label: "plate (restaurant ~180g)", weight_grams: 180, calories_kcal: 414, protein_g: 10.8, carbs_g: 54.0, fat_g: 18.0, fiber_g: 4.5, sodium_mg: 684, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Recipe analysis" }], aliases: [{ alias_text: "Tokri Chaat", language: "en", script: "latin" }] },
  { canonical_name: "fruit chaat", display_name_en: "Fruit Chaat", category: "salad", subcategory: "bowl", cuisine_region: "north_indian", meal_type: "snack", cooking_method: "raw", is_veg: true, is_vegan: true, is_jain: false, allergens: [], glycemic_index: 45, data_source: "recipe_analysis", data_quality_score: 75, verified: false, per_100g: { calories_kcal: 95, protein_g: 1.5, carbs_g: 20.0, fat_g: 0.8, fiber_g: 2.5, sugar_g: 14.0, sodium_mg: 120, saturated_fat_g: 0.1 }, portions: [{ label: "bowl (restaurant ~250g)", weight_grams: 250, calories_kcal: 238, protein_g: 3.8, carbs_g: 50.0, fat_g: 2.0, fiber_g: 6.3, sodium_mg: 300, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Fruit-based, minimal adjustment" }], aliases: [{ alias_text: "Phalon Ki Chaat", language: "en", script: "latin" }] },
  // MUMBAI STREET FOOD
  // Vada Pav: Tarladalal=197kcal/piece (~248kcal/100g for 80g piece)
  { canonical_name: "vada pav", display_name_en: "Vada Pav", category: "snack", subcategory: "burger", cuisine_region: "south_indian", meal_type: "snack", cooking_method: "fried", is_veg: true, is_vegan: true, is_jain: false, allergens: ["gluten"], glycemic_index: 68, data_source: "recipe_analysis", data_quality_score: 82, verified: false, per_100g: { calories_kcal: 248, protein_g: 6.0, carbs_g: 32.0, fat_g: 11.0, fiber_g: 2.5, sugar_g: 2.5, sodium_mg: 320, saturated_fat_g: 2.0 }, portions: [{ label: "burger (1 piece ~80g)", weight_grams: 80, calories_kcal: 198, protein_g: 4.8, carbs_g: 25.6, fat_g: 8.8, fiber_g: 2.0, sodium_mg: 256, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Tarladalal verified: 197kcal/piece" }], aliases: [{ alias_text: "Batata Vada Pav", language: "en", script: "latin" }, { alias_text: "Mumbai Burger", language: "en", script: "latin" }] },
  // Misal Pav: Tarladalal=289kcal/serving (~185kcal/100g)
  { canonical_name: "misal pav", display_name_en: "Misal Pav", category: "snack", subcategory: "plate", cuisine_region: "south_indian", meal_type: "breakfast", cooking_method: "boiled", is_veg: true, is_vegan: true, is_jain: false, allergens: ["gluten"], glycemic_index: 55, data_source: "recipe_analysis", data_quality_score: 80, verified: false, per_100g: { calories_kcal: 185, protein_g: 9.0, carbs_g: 26.0, fat_g: 6.0, fiber_g: 5.0, sugar_g: 2.0, sodium_mg: 380, saturated_fat_g: 1.0 }, portions: [{ label: "plate (restaurant ~300g)", weight_grams: 300, calories_kcal: 555, protein_g: 27.0, carbs_g: 78.0, fat_g: 18.0, fiber_g: 15.0, sodium_mg: 1140, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Tarladalal verified: 289kcal/serving" }], aliases: [{ alias_text: "Misal", language: "en", script: "latin" }] },
  { canonical_name: "dabeli", display_name_en: "Dabeli", category: "snack", subcategory: "burger", cuisine_region: "south_indian", meal_type: "snack", cooking_method: "raw", is_veg: true, is_vegan: false, is_jain: false, allergens: ["gluten", "peanuts"], glycemic_index: 62, data_source: "recipe_analysis", data_quality_score: 70, verified: false, per_100g: { calories_kcal: 238, protein_g: 6.0, carbs_g: 34.0, fat_g: 9.0, fiber_g: 2.5, sugar_g: 5.0, sodium_mg: 360, saturated_fat_g: 2.0 }, portions: [{ label: "burger (1 piece ~150g)", weight_grams: 150, calories_kcal: 357, protein_g: 9.0, carbs_g: 51.0, fat_g: 13.5, fiber_g: 3.8, sodium_mg: 540, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Recipe analysis" }], aliases: [{ alias_text: "Kutchi Dabeli", language: "en", script: "latin" }] },
  { canonical_name: "tawa pulao", display_name_en: "Tawa Pulao", category: "rice_dish", subcategory: "plate", cuisine_region: "south_indian", meal_type: "lunch_dinner", cooking_method: "fried", is_veg: true, is_vegan: true, is_jain: false, allergens: [], glycemic_index: 65, data_source: "recipe_analysis", data_quality_score: 70, verified: false, per_100g: { calories_kcal: 148, protein_g: 4.0, carbs_g: 22.0, fat_g: 5.0, fiber_g: 1.5, sugar_g: 2.0, sodium_mg: 420, saturated_fat_g: 0.8 }, portions: [{ label: "plate (restaurant ~300g)", weight_grams: 300, calories_kcal: 444, protein_g: 12.0, carbs_g: 66.0, fat_g: 15.0, fiber_g: 4.5, sodium_mg: 1260, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Recipe analysis" }], aliases: [{ alias_text: "Mumbai Tawa Pulao", language: "en", script: "latin" }] },
  { canonical_name: "batata vada", display_name_en: "Batata Vada", category: "snack", subcategory: "vada", cuisine_region: "south_indian", meal_type: "snack", cooking_method: "fried", is_veg: true, is_vegan: true, is_jain: false, allergens: ["gluten"], glycemic_index: 65, data_source: "recipe_analysis", data_quality_score: 75, verified: false, per_100g: { calories_kcal: 215, protein_g: 4.0, carbs_g: 26.0, fat_g: 11.0, fiber_g: 2.0, sugar_g: 1.5, sodium_mg: 310, saturated_fat_g: 1.5 }, portions: [{ label: "vada (1 piece ~100g)", weight_grams: 100, calories_kcal: 215, protein_g: 4.0, carbs_g: 26.0, fat_g: 11.0, fiber_g: 2.0, sodium_mg: 310, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Recipe analysis" }], aliases: [{ alias_text: "Aloo Vada", language: "en", script: "latin" }] },
  { canonical_name: "bombay sandwich", display_name_en: "Bombay Sandwich", category: "snack", subcategory: "sandwich", cuisine_region: "south_indian", meal_type: "snack", cooking_method: "raw", is_veg: true, is_vegan: false, is_jain: false, allergens: ["gluten", "dairy"], glycemic_index: 58, data_source: "recipe_analysis", data_quality_score: 70, verified: false, per_100g: { calories_kcal: 218, protein_g: 7.0, carbs_g: 28.0, fat_g: 9.0, fiber_g: 2.5, sugar_g: 3.0, sodium_mg: 480, saturated_fat_g: 3.5 }, portions: [{ label: "sandwich (1 piece ~200g)", weight_grams: 200, calories_kcal: 436, protein_g: 14.0, carbs_g: 56.0, fat_g: 18.0, fiber_g: 5.0, sodium_mg: 960, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Recipe analysis" }], aliases: [{ alias_text: "Mumbai Sandwich", language: "en", script: "latin" }, { alias_text: "Masala Sandwich", language: "en", script: "latin" }] },
  // DELHI / NORTH INDIAN STREET FOOD
  { canonical_name: "chole kulche", display_name_en: "Chole Kulche", category: "snack", subcategory: "plate", cuisine_region: "north_indian", meal_type: "breakfast", cooking_method: "boiled", is_veg: true, is_vegan: true, is_jain: false, allergens: ["gluten"], glycemic_index: 62, data_source: "recipe_analysis", data_quality_score: 75, verified: false, per_100g: { calories_kcal: 195, protein_g: 8.0, carbs_g: 30.0, fat_g: 5.0, fiber_g: 4.5, sugar_g: 2.0, sodium_mg: 380, saturated_fat_g: 0.8 }, portions: [{ label: "plate (restaurant ~320g)", weight_grams: 320, calories_kcal: 624, protein_g: 25.6, carbs_g: 96.0, fat_g: 16.0, fiber_g: 14.4, sodium_mg: 1216, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Recipe analysis" }], aliases: [{ alias_text: "Kulche Chole", language: "en", script: "latin" }] },
  { canonical_name: "tikki chole", display_name_en: "Tikki Chole", category: "snack", subcategory: "plate", cuisine_region: "north_indian", meal_type: "snack", cooking_method: "fried", is_veg: true, is_vegan: true, is_jain: false, allergens: ["gluten"], glycemic_index: 62, data_source: "recipe_analysis", data_quality_score: 70, verified: false, per_100g: { calories_kcal: 200, protein_g: 7.0, carbs_g: 27.0, fat_g: 8.0, fiber_g: 3.5, sugar_g: 3.0, sodium_mg: 400, saturated_fat_g: 1.2 }, portions: [{ label: "plate (restaurant ~280g)", weight_grams: 280, calories_kcal: 560, protein_g: 19.6, carbs_g: 75.6, fat_g: 22.4, fiber_g: 9.8, sodium_mg: 1120, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Recipe analysis" }], aliases: [{ alias_text: "Aloo Tikki Chole", language: "en", script: "latin" }] },
  { canonical_name: "kachori sabzi", display_name_en: "Kachori Sabzi", category: "snack", subcategory: "plate", cuisine_region: "north_indian", meal_type: "breakfast", cooking_method: "fried", is_veg: true, is_vegan: true, is_jain: false, allergens: ["gluten"], glycemic_index: 62, data_source: "recipe_analysis", data_quality_score: 70, verified: false, per_100g: { calories_kcal: 348, protein_g: 7.0, carbs_g: 35.0, fat_g: 20.0, fiber_g: 3.5, sugar_g: 2.0, sodium_mg: 380, saturated_fat_g: 3.0 }, portions: [{ label: "plate (restaurant ~250g)", weight_grams: 250, calories_kcal: 870, protein_g: 17.5, carbs_g: 87.5, fat_g: 50.0, fiber_g: 8.8, sodium_mg: 950, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Deep fried, high calorie" }], aliases: [{ alias_text: "Kachori with Sabzi", language: "en", script: "latin" }] },
  { canonical_name: "halwa poori", display_name_en: "Halwa Poori", category: "snack", subcategory: "plate", cuisine_region: "north_indian", meal_type: "breakfast", cooking_method: "fried", is_veg: true, is_vegan: false, is_jain: false, allergens: ["gluten", "dairy"], glycemic_index: 68, data_source: "recipe_analysis", data_quality_score: 70, verified: false, per_100g: { calories_kcal: 310, protein_g: 6.0, carbs_g: 38.0, fat_g: 15.0, fiber_g: 2.0, sugar_g: 8.0, sodium_mg: 280, saturated_fat_g: 5.0 }, portions: [{ label: "plate (restaurant ~300g)", weight_grams: 300, calories_kcal: 930, protein_g: 18.0, carbs_g: 114.0, fat_g: 45.0, fiber_g: 6.0, sodium_mg: 840, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Deep fried + sweet halwa, high calorie" }], aliases: [{ alias_text: "Puri Halwa", language: "en", script: "latin" }, { alias_text: "Halwa Puri", language: "en", script: "latin" }] },
  // SOUTH INDIAN STREET FOOD
  // Medu Vada: Tarladalal=97kcal/piece (~295kcal/100g for 33g piece)
  { canonical_name: "medu vada", display_name_en: "Medu Vada", category: "south_indian", subcategory: "vada", cuisine_region: "south_indian", meal_type: "breakfast", cooking_method: "fried", is_veg: true, is_vegan: true, is_jain: false, allergens: ["gluten"], glycemic_index: 45, data_source: "recipe_analysis", data_quality_score: 82, verified: false, per_100g: { calories_kcal: 295, protein_g: 8.0, carbs_g: 28.0, fat_g: 16.0, fiber_g: 2.5, sugar_g: 1.0, sodium_mg: 380, saturated_fat_g: 2.5 }, portions: [{ label: "vada (2 pieces ~120g)", weight_grams: 120, calories_kcal: 354, protein_g: 9.6, carbs_g: 33.6, fat_g: 19.2, fiber_g: 3.0, sodium_mg: 456, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Tarladalal verified: 97kcal/piece" }], aliases: [{ alias_text: "Uzhunnu Vada", language: "en", script: "latin" }, { alias_text: "Ulundu Vadai", language: "en", script: "latin" }] },
  // Rava Idli: ClearCals=183kcal/100g
  { canonical_name: "rava idli", display_name_en: "Rava Idli", category: "south_indian", subcategory: "idli", cuisine_region: "south_indian", meal_type: "breakfast", cooking_method: "steamed", is_veg: true, is_vegan: false, is_jain: false, allergens: ["dairy"], glycemic_index: 35, data_source: "recipe_analysis", data_quality_score: 80, verified: false, per_100g: { calories_kcal: 148, protein_g: 4.0, carbs_g: 24.0, fat_g: 4.0, fiber_g: 1.5, sugar_g: 1.5, sodium_mg: 280, saturated_fat_g: 1.5 }, portions: [{ label: "idli (3 pieces ~150g)", weight_grams: 150, calories_kcal: 222, protein_g: 6.0, carbs_g: 36.0, fat_g: 6.0, fiber_g: 2.3, sodium_mg: 420, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "ClearCals verified: 183kcal/100g" }], aliases: [{ alias_text: "Semolina Idli", language: "en", script: "latin" }, { alias_text: "Suji Idli", language: "en", script: "latin" }] },
  { canonical_name: "mini idli sambar", display_name_en: "Mini Idli Sambar", category: "south_indian", subcategory: "plate", cuisine_region: "south_indian", meal_type: "breakfast", cooking_method: "steamed", is_veg: true, is_vegan: true, is_jain: false, allergens: [], glycemic_index: 40, data_source: "recipe_analysis", data_quality_score: 75, verified: false, per_100g: { calories_kcal: 112, protein_g: 4.0, carbs_g: 18.0, fat_g: 3.0, fiber_g: 2.0, sugar_g: 1.5, sodium_mg: 320, saturated_fat_g: 0.5 }, portions: [{ label: "plate (12 pieces + sambar ~300g)", weight_grams: 300, calories_kcal: 336, protein_g: 12.0, carbs_g: 54.0, fat_g: 9.0, fiber_g: 6.0, sodium_mg: 960, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Recipe analysis" }], aliases: [{ alias_text: "Button Idli", language: "en", script: "latin" }] },
  { canonical_name: "pesarattu", display_name_en: "Pesarattu", category: "south_indian", subcategory: "dosa", cuisine_region: "south_indian", meal_type: "breakfast", cooking_method: "fried", is_veg: true, is_vegan: true, is_jain: false, allergens: [], glycemic_index: 45, data_source: "recipe_analysis", data_quality_score: 75, verified: false, per_100g: { calories_kcal: 165, protein_g: 7.0, carbs_g: 24.0, fat_g: 5.0, fiber_g: 3.0, sugar_g: 1.0, sodium_mg: 280, saturated_fat_g: 0.8 }, portions: [{ label: "dosa (1 piece ~150g)", weight_grams: 150, calories_kcal: 248, protein_g: 10.5, carbs_g: 36.0, fat_g: 7.5, fiber_g: 4.5, sodium_mg: 420, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Recipe analysis" }], aliases: [{ alias_text: "Green Moong Dosa", language: "en", script: "latin" }, { alias_text: "Moong Dal Dosa", language: "en", script: "latin" }] },
  { canonical_name: "vada sambar", display_name_en: "Vada Sambar", category: "south_indian", subcategory: "plate", cuisine_region: "south_indian", meal_type: "breakfast", cooking_method: "fried", is_veg: true, is_vegan: true, is_jain: false, allergens: ["gluten"], glycemic_index: 48, data_source: "recipe_analysis", data_quality_score: 75, verified: false, per_100g: { calories_kcal: 198, protein_g: 7.0, carbs_g: 22.0, fat_g: 9.0, fiber_g: 2.5, sugar_g: 1.5, sodium_mg: 380, saturated_fat_g: 1.5 }, portions: [{ label: "plate (2 vadas + sambar ~250g)", weight_grams: 250, calories_kcal: 495, protein_g: 17.5, carbs_g: 55.0, fat_g: 22.5, fiber_g: 6.3, sodium_mg: 950, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Recipe analysis" }], aliases: [{ alias_text: "Medu Vada Sambar", language: "en", script: "latin" }] },
  { canonical_name: "bonda", display_name_en: "Bonda", category: "south_indian", subcategory: "bonda", cuisine_region: "south_indian", meal_type: "snack", cooking_method: "fried", is_veg: true, is_vegan: true, is_jain: false, allergens: ["gluten"], glycemic_index: 60, data_source: "recipe_analysis", data_quality_score: 75, verified: false, per_100g: { calories_kcal: 265, protein_g: 5.0, carbs_g: 28.0, fat_g: 15.0, fiber_g: 2.0, sugar_g: 1.5, sodium_mg: 360, saturated_fat_g: 2.0 }, portions: [{ label: "bonda (2 pieces ~120g)", weight_grams: 120, calories_kcal: 318, protein_g: 6.0, carbs_g: 33.6, fat_g: 18.0, fiber_g: 2.4, sodium_mg: 432, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Recipe analysis" }], aliases: [{ alias_text: "Aloo Bonda", language: "en", script: "latin" }, { alias_text: "Potato Bonda", language: "en", script: "latin" }] },
  // GUJARATI STREET FOOD
  // Dhokla: SnapCalorie=133kcal/100g (P:4g C:23g F:3g) - confirmed by multiple sources
  { canonical_name: "dhokla", display_name_en: "Dhokla", category: "south_indian", subcategory: "dhokla", cuisine_region: "south_indian", meal_type: "breakfast", cooking_method: "steamed", is_veg: true, is_vegan: true, is_jain: false, allergens: [], glycemic_index: 35, data_source: "recipe_analysis", data_quality_score: 82, verified: false, per_100g: { calories_kcal: 145, protein_g: 6.0, carbs_g: 22.0, fat_g: 4.0, fiber_g: 1.5, sugar_g: 3.0, sodium_mg: 280, saturated_fat_g: 0.5 }, portions: [{ label: "plate (6 pieces ~200g)", weight_grams: 200, calories_kcal: 290, protein_g: 12.0, carbs_g: 44.0, fat_g: 8.0, fiber_g: 3.0, sodium_mg: 560, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "SnapCalorie verified: 133kcal/100g" }], aliases: [{ alias_text: "Khaman Dhokla", language: "en", script: "latin" }, { alias_text: "Besan Dhokla", language: "en", script: "latin" }] },
  // Khandvi: Tarladalal=42kcal/piece (~165kcal/100g for 25g piece)
  { canonical_name: "khandvi", display_name_en: "Khandvi", category: "snack", subcategory: "plate", cuisine_region: "south_indian", meal_type: "snack", cooking_method: "boiled", is_veg: true, is_vegan: false, is_jain: false, allergens: ["dairy"], glycemic_index: 38, data_source: "recipe_analysis", data_quality_score: 80, verified: false, per_100g: { calories_kcal: 165, protein_g: 7.0, carbs_g: 20.0, fat_g: 6.0, fiber_g: 1.5, sugar_g: 2.5, sodium_mg: 260, saturated_fat_g: 2.5 }, portions: [{ label: "plate (restaurant ~150g)", weight_grams: 150, calories_kcal: 248, protein_g: 10.5, carbs_g: 30.0, fat_g: 9.0, fiber_g: 2.3, sodium_mg: 390, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Tarladalal verified: 42kcal/piece" }], aliases: [{ alias_text: "Patuli", language: "en", script: "latin" }] },
  // Handvo: Tarladalal=216kcal/serving (~198kcal/100g)
  { canonical_name: "handvo", display_name_en: "Handvo", category: "snack", subcategory: "slice", cuisine_region: "south_indian", meal_type: "breakfast", cooking_method: "baked", is_veg: true, is_vegan: true, is_jain: false, allergens: ["gluten"], glycemic_index: 45, data_source: "recipe_analysis", data_quality_score: 80, verified: false, per_100g: { calories_kcal: 198, protein_g: 7.0, carbs_g: 25.0, fat_g: 8.0, fiber_g: 3.5, sugar_g: 2.0, sodium_mg: 320, saturated_fat_g: 1.2 }, portions: [{ label: "slice (restaurant ~200g)", weight_grams: 200, calories_kcal: 396, protein_g: 14.0, carbs_g: 50.0, fat_g: 16.0, fiber_g: 7.0, sodium_mg: 640, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Tarladalal verified: 216kcal/serving" }], aliases: [{ alias_text: "Gujarati Handvo", language: "en", script: "latin" }] },
  { canonical_name: "muthia", display_name_en: "Muthia", category: "snack", subcategory: "muthia", cuisine_region: "south_indian", meal_type: "snack", cooking_method: "steamed", is_veg: true, is_vegan: true, is_jain: false, allergens: ["gluten"], glycemic_index: 42, data_source: "recipe_analysis", data_quality_score: 75, verified: false, per_100g: { calories_kcal: 175, protein_g: 6.0, carbs_g: 24.0, fat_g: 6.0, fiber_g: 3.0, sugar_g: 2.0, sodium_mg: 280, saturated_fat_g: 0.8 }, portions: [{ label: "muthia (restaurant ~180g)", weight_grams: 180, calories_kcal: 315, protein_g: 10.8, carbs_g: 43.2, fat_g: 10.8, fiber_g: 5.4, sodium_mg: 504, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Recipe analysis" }], aliases: [{ alias_text: "Methi Muthia", language: "en", script: "latin" }] },
  { canonical_name: "sev khamani", display_name_en: "Sev Khamani", category: "snack", subcategory: "plate", cuisine_region: "south_indian", meal_type: "snack", cooking_method: "boiled", is_veg: true, is_vegan: true, is_jain: false, allergens: ["gluten"], glycemic_index: 45, data_source: "recipe_analysis", data_quality_score: 70, verified: false, per_100g: { calories_kcal: 188, protein_g: 6.0, carbs_g: 24.0, fat_g: 8.0, fiber_g: 2.5, sugar_g: 3.0, sodium_mg: 300, saturated_fat_g: 1.0 }, portions: [{ label: "plate (restaurant ~200g)", weight_grams: 200, calories_kcal: 376, protein_g: 12.0, carbs_g: 48.0, fat_g: 16.0, fiber_g: 5.0, sodium_mg: 600, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Recipe analysis" }], aliases: [{ alias_text: "Sev Khamni", language: "en", script: "latin" }] },
  { canonical_name: "undhiyu", display_name_en: "Undhiyu", category: "curry", subcategory: "bowl", cuisine_region: "south_indian", meal_type: "lunch_dinner", cooking_method: "boiled", is_veg: true, is_vegan: true, is_jain: false, allergens: [], glycemic_index: 45, data_source: "recipe_analysis", data_quality_score: 70, verified: false, per_100g: { calories_kcal: 165, protein_g: 5.0, carbs_g: 18.0, fat_g: 9.0, fiber_g: 4.0, sugar_g: 2.5, sodium_mg: 280, saturated_fat_g: 1.2 }, portions: [{ label: "bowl (restaurant ~250g)", weight_grams: 250, calories_kcal: 413, protein_g: 12.5, carbs_g: 45.0, fat_g: 22.5, fiber_g: 10.0, sodium_mg: 700, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Recipe analysis" }], aliases: [{ alias_text: "Oondhiyu", language: "en", script: "latin" }] },
  // CONDIMENTS AND ACCOMPANIMENTS (affect total meal calories)
  // Green Chutney: SnapCalorie=80kcal/100g (P:2g C:12g F:2g)
  { canonical_name: "green chutney", display_name_en: "Green Chutney", category: "other", subcategory: "tablespoon", cuisine_region: "pan_indian", meal_type: "any", cooking_method: "raw", is_veg: true, is_vegan: true, is_jain: false, allergens: [], glycemic_index: 20, data_source: "recipe_analysis", data_quality_score: 78, verified: false, per_100g: { calories_kcal: 80, protein_g: 2.0, carbs_g: 12.0, fat_g: 2.0, fiber_g: 3.0, sugar_g: 2.0, sodium_mg: 280, saturated_fat_g: 0.2 }, portions: [{ label: "tablespoon (~30g)", weight_grams: 30, calories_kcal: 24, protein_g: 0.6, carbs_g: 3.6, fat_g: 0.6, fiber_g: 0.9, sodium_mg: 84, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Condiment: standardized" }], aliases: [{ alias_text: "Hari Chutney", language: "en", script: "latin" }, { alias_text: "Mint Coriander Chutney", language: "en", script: "latin" }, { alias_text: "Dhaniya Pudina Chutney", language: "en", script: "latin" }] },
  // Tamarind Chutney: high sugar, ~185kcal/100g
  { canonical_name: "tamarind chutney", display_name_en: "Tamarind Chutney", category: "other", subcategory: "tablespoon", cuisine_region: "pan_indian", meal_type: "any", cooking_method: "boiled", is_veg: true, is_vegan: true, is_jain: false, allergens: [], glycemic_index: 65, data_source: "recipe_analysis", data_quality_score: 75, verified: false, per_100g: { calories_kcal: 185, protein_g: 1.0, carbs_g: 45.0, fat_g: 0.5, fiber_g: 2.0, sugar_g: 38.0, sodium_mg: 320, saturated_fat_g: 0.1 }, portions: [{ label: "tablespoon (~30g)", weight_grams: 30, calories_kcal: 56, protein_g: 0.3, carbs_g: 13.5, fat_g: 0.2, fiber_g: 0.6, sodium_mg: 96, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Condiment: standardized" }], aliases: [{ alias_text: "Imli Chutney", language: "en", script: "latin" }, { alias_text: "Sweet Chutney", language: "en", script: "latin" }, { alias_text: "Meethi Chutney", language: "en", script: "latin" }] },
  // Dry Garlic Chutney: ~420kcal/100g (high fat from peanuts/coconut)
  { canonical_name: "dry garlic chutney", display_name_en: "Dry Garlic Chutney", category: "other", subcategory: "teaspoon", cuisine_region: "south_indian", meal_type: "any", cooking_method: "raw", is_veg: true, is_vegan: true, is_jain: false, allergens: ["peanuts"], glycemic_index: 25, data_source: "recipe_analysis", data_quality_score: 70, verified: false, per_100g: { calories_kcal: 420, protein_g: 12.0, carbs_g: 28.0, fat_g: 30.0, fiber_g: 5.0, sugar_g: 3.0, sodium_mg: 480, saturated_fat_g: 5.0 }, portions: [{ label: "teaspoon (~15g)", weight_grams: 15, calories_kcal: 63, protein_g: 1.8, carbs_g: 4.2, fat_g: 4.5, fiber_g: 0.8, sodium_mg: 72, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Condiment: standardized" }], aliases: [{ alias_text: "Lasun Chutney", language: "en", script: "latin" }, { alias_text: "Garlic Chutney Dry", language: "en", script: "latin" }] },
  // Ragda (white peas curry): ~115kcal/100g
  { canonical_name: "ragda", display_name_en: "Ragda", category: "dal", subcategory: "small bowl", cuisine_region: "south_indian", meal_type: "snack", cooking_method: "boiled", is_veg: true, is_vegan: true, is_jain: false, allergens: [], glycemic_index: 45, data_source: "recipe_analysis", data_quality_score: 72, verified: false, per_100g: { calories_kcal: 115, protein_g: 5.5, carbs_g: 18.0, fat_g: 3.0, fiber_g: 4.5, sugar_g: 1.5, sodium_mg: 280, saturated_fat_g: 0.5 }, portions: [{ label: "small bowl (~150g)", weight_grams: 150, calories_kcal: 173, protein_g: 8.3, carbs_g: 27.0, fat_g: 4.5, fiber_g: 6.8, sodium_mg: 420, is_default: true, restaurant_multiplier_applied: 1.0, multiplier_note: "Condiment/accompaniment" }], aliases: [{ alias_text: "White Peas Curry", language: "en", script: "latin" }, { alias_text: "Vatana Ragda", language: "en", script: "latin" }] },
];

async function seed() {
  const MONGODB_URI = process.env.MONGODB_URI;
  if (!MONGODB_URI) { console.error("[seed:street] MONGODB_URI not found."); process.exit(1); }
  console.log("[seed:street] Connecting to MongoDB...");
  await mongoose.connect(MONGODB_URI);
  console.log("[seed:street] Connected.");
  const { default: FoodItem } = await import("../models/FoodItem.model.js");
  let upserted = 0, errors = 0;
  for (const dish of STREET_FOOD_DISHES) {
    try {
      await FoodItem.updateOne({ canonical_name: dish.canonical_name }, { $set: { ...dish, last_updated: new Date() } }, { upsert: true });
      upserted++;
    } catch (err) {
      errors++;
      console.error(`[seed:street] Error on "${dish.display_name_en}":`, err.message);
    }
  }
  console.log(`\n[seed:street] Done! Upserted: ${upserted}/${STREET_FOOD_DISHES.length}, Errors: ${errors}`);
  await mongoose.disconnect();
  process.exit(0);
}
seed().catch(err => { console.error("[seed:street] Fatal:", err); process.exit(1); });
